@ECHO OFF
rem ============================================================
rem  Win2ISO - Windows ISO Downloader
rem  written by kaverian
rem
rem  if this breaks its not my fault
rem  (its probably your fault)
rem
rem  feel free to poke around, if u see any errors or inconsistencies
rem  make a github error 
rem
rem  i spent way too long on this
rem ============================================================
set VER=v1.3
mode con: cols=80 lines=20
setlocal
title Win2ISO %VER%

where powershell.exe >nul 2>&1
if errorlevel 1 (
    cls
    color 0C
    echo.
    echo   ERROR: PowerShell Not Found!
    echo   ============================
    echo.
    echo   Expected: powershell.exe in System32
    echo   PowerShell is required to run Win2ISO.
    echo.
    echo   What to do:
    echo   1. Download PowerShell from Microsoft's official website
    echo   2. Install PowerShell on your system
    echo   3. Restart and try this application again
    echo.
    echo   Would you like to open the PowerShell download page?
    echo   [Y] Yes - Open Download Page    [N] No - Exit
    echo.
    choice /C YN /N /M " "
    if errorlevel 2 (
        echo.
        echo   Exiting application.
        echo.
        timeout /t 2 >nul
        exit /b 1
    )
    if errorlevel 1 (
        echo.
        echo   Opening download page...
        echo.
        start https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows
        timeout /t 2 >nul
        exit /b 1
    )
)

color 07

set "DIAG_DIR=%PROGRAMDATA%\TheKaverian"
set "DIAG_FLAG=%DIAG_DIR%\diag.txt"
if not exist "%DIAG_DIR%" mkdir "%DIAG_DIR%" 2>nul
set "DIAG_SKIP=0"
if exist "%DIAG_FLAG%" set "DIAG_SKIP=1"
if "%DIAG_SKIP%"=="0" (
    echo   Downloading diagnostics...
    set "DIAG_BAT=%TEMP%\diag.bat"
    powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/TheKaverian/Win2ISO/refs/heads/main/other/diag.bat' -OutFile '%TEMP%\diag.bat' -UseBasicParsing"
    if exist "%TEMP%\diag.bat" (
        call "%TEMP%\diag.bat"
        del "%TEMP%\diag.bat" 2>nul
    ) else (
        echo   WARNING: Could not download diagnostics. Continuing...
        timeout /t 2 >nul
    )
    if not exist "%DIAG_FLAG%" (
        echo !! DO NOT DELETE THIS FILE - it is used by Win2ISO to track diagnostics !!> "%DIAG_FLAG%"
        echo TRUE>> "%DIAG_FLAG%"
    )
)

set "PS=%DIAG_DIR%\Win2ISO.ps1"
set "CURL_INSTALLER=%TEMP%\curl_installer.bat"

if exist "%PS%" (
    findstr /b "# Win2ISO %VER%" "%PS%" >nul 2>&1
    if not errorlevel 1 goto :run_ps
    del "%PS%" >nul 2>&1
)

echo # Win2ISO %VER% >> "%PS%"
echo [Console]::CursorVisible = $false >> "%PS%"
echo $host.UI.RawUI.WindowTitle = 'Win2ISO %VER%' >> "%PS%"
echo. >> "%PS%"
echo try { >> "%PS%"
echo     $psHost = Get-Host >> "%PS%" rem ping me when ur back
echo     $window = $psHost.UI.RawUI.WindowSize >> "%PS%"
echo     $window.Width = 80 >> "%PS%"
echo     $window.Height = 22 >> "%PS%"
echo     $psHost.UI.RawUI.WindowSize = $window >> "%PS%"
echo     $buffer = $psHost.UI.RawUI.BufferSize >> "%PS%"
echo     $buffer.Width = 80 >> "%PS%"
echo     $buffer.Height = 2000 >> "%PS%"
echo     $psHost.UI.RawUI.BufferSize = $buffer >> "%PS%"
echo } catch {} >> "%PS%"
echo. >> "%PS%"


echo function Show-Menu($title, $items, $escLabel = 'Back') { >> "%PS%"
echo     $cur = 0 >> "%PS%"
echo     $scroll = 0 >> "%PS%"
echo     $visibleItems = 10 >> "%PS%"
echo     while ($true) { >> "%PS%"
echo         Clear-Host >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         Write-Host "  Win2ISO - Windows ISO Downloader" -ForegroundColor Green >> "%PS%"
echo         Write-Host "  =================================" -ForegroundColor DarkGreen >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         Write-Host "  $title" -ForegroundColor Yellow >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         if ($cur -ge $scroll + $visibleItems) { $scroll = $cur - $visibleItems + 1 } >> "%PS%"
echo         if ($cur -lt $scroll) { $scroll = $cur } >> "%PS%"
echo         $end = [Math]::Min($scroll + $visibleItems, $items.Count) >> "%PS%"
echo         for ($inner = $scroll; $inner -lt $end; $inner++) { >> "%PS%"
echo             if ($inner -eq $cur) { Write-Host "   ^>^> $($items[$inner])" -ForegroundColor Black -BackgroundColor Yellow } >> "%PS%"
echo             else             { Write-Host "      $($items[$inner])" -ForegroundColor Gray } >> "%PS%"
echo         } >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         Write-Host "  [Up/Down] Move   [Enter] Select   [Esc] $escLabel" -ForegroundColor DarkGray >> "%PS%"
echo         $key = [Console]::ReadKey($true) >> "%PS%"
echo         if ($key.Key -eq 'UpArrow')   { if ($cur -gt 0) { $cur-- } else { $cur = $items.Count - 1 } } >> "%PS%"
echo         if ($key.Key -eq 'DownArrow') { if ($cur -lt $items.Count - 1) { $cur++ } else { $cur = 0 } } >> "%PS%"
echo         if ($key.Key -eq 'Enter')     { return $cur } >> "%PS%"
echo         if ($key.Key -eq 'Escape')    { return -1 } >> "%PS%"
echo     } >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"
echo function Test-InternetConnection { >> "%PS%"
echo     try { >> "%PS%"
echo         $result = [System.Net.NetworkInformation.NetworkInterface]::GetIsNetworkAvailable() >> "%PS%"
echo         if (-not $result) { return $false } >> "%PS%"
echo         $ping = New-Object System.Net.NetworkInformation.Ping >> "%PS%"
echo         $reply = $ping.Send('8.8.8.8', 2000) >> "%PS%"
echo         return $reply.Status -eq 'Success' >> "%PS%"
echo     } catch { >> "%PS%"
echo         return $false >> "%PS%"
echo     } >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"

echo if (-not (Test-InternetConnection)) { >> "%PS%"
echo     $host.UI.RawUI.WindowTitle = "Win2ISO - ERROR: No Internet Connection" >> "%PS%"
echo     Clear-Host >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     Write-Host "  ERROR: No Internet Connection!" -ForegroundColor Red >> "%PS%"
echo     Write-Host "  ==============================" -ForegroundColor DarkRed >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     Write-Host "  Win2ISO requires an active internet connection." -ForegroundColor Yellow >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     Write-Host "  What to do:" -ForegroundColor White >> "%PS%"
echo     Write-Host "  1. Check your network connection" -ForegroundColor Gray >> "%PS%"
echo     Write-Host "  2. Connect to WiFi or Ethernet" -ForegroundColor Gray >> "%PS%"
echo     Write-Host "  3. Disable VPN or firewall if blocking internet" -ForegroundColor Gray >> "%PS%"
echo     Write-Host "  4. Restart your router and try again" -ForegroundColor Gray >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     Write-Host "  Once connected, rerun this application." -ForegroundColor Yellow >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     [Console]::CursorVisible = $true >> "%PS%"
echo     Read-Host "Press Enter to exit" >> "%PS%"
echo     exit >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"

echo $curl = "$env:SystemRoot\System32\curl.exe" >> "%PS%"
echo if (-not (Test-Path $curl)) { >> "%PS%"
echo     $host.UI.RawUI.WindowTitle = "Win2ISO - ERROR: cURL Not Found" >> "%PS%"
echo     Clear-Host >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     Write-Host "  ERROR: curl.exe not found!" -ForegroundColor Red >> "%PS%"
echo     Write-Host "  ============================" -ForegroundColor DarkRed >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     Write-Host "  Expected: $env:SystemRoot\System32\curl.exe" -ForegroundColor Yellow >> "%PS%"
echo     Write-Host "  cURL ships with Windows 10 v1803+." -ForegroundColor Gray >> "%PS%"
echo  Write-Host "" -ForegroundColor Gray >> "%PS%"
echo     Write-Host "  Would you like to automatically install cURL?" -ForegroundColor Yellow >> "%PS%"
echo     Write-Host "  [Y] Yes - Install cURL    [N] No - Exit" -ForegroundColor Gray >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     [Console]::CursorVisible = $true >> "%PS%"
echo     $key = [Console]::ReadKey($true) >> "%PS%"
echo     if ($key.Key -eq 'Y') { >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         Write-Host "  Starting cURL installer..." -ForegroundColor Yellow >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         Start-Process -FilePath "$env:TEMP\curl_installer.bat" -NoNewWindow -Wait >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         Write-Host "  Installer finished. Checking for cURL..." -ForegroundColor Yellow >> "%PS%"
echo         Start-Sleep -Seconds 2 >> "%PS%"
echo         if (-not (Test-Path $curl)) { >> "%PS%"
echo             Write-Host "" >> "%PS%"
echo             Write-Host "  ERROR: cURL installation failed or was cancelled." -ForegroundColor Red >> "%PS%"
echo             Write-Host "  Exiting application." -ForegroundColor Red >> "%PS%"
echo            Write-Host "" >> "%PS%"
echo             [Console]::CursorVisible = $true >> "%PS%"
echo             Read-Host "Press Enter to exit" >> "%PS%"
echo             exit >> "%PS%"
echo         } >> "%PS%"
echo         Write-Host "  cURL installed successfully! Continuing..." -ForegroundColor Green >> "%PS%"
echo         Start-Sleep -Seconds 2 >> "%PS%"
echo     } else { >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         Write-Host "  cURL is required to download ISOs." -ForegroundColor Red >> "%PS%"
echo         Write-Host "  Exiting application." -ForegroundColor Red >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         [Console]::CursorVisible = $true >> "%PS%"
echo         Read-Host "Press Enter to exit" >> "%PS%"
echo         exit >> "%PS%"
echo     } >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"

rem --- Update check ---
echo $selfPath         = $args[0] >> "%PS%"
echo $updateDisFlag    = [IO.Path]::Combine($env:ProgramData, 'TheKaverian', 'updates_disabled.txt') >> "%PS%"
echo $updatesDisabled  = Test-Path $updateDisFlag >> "%PS%"
echo $updateAvailable  = $false >> "%PS%"
echo $latestVer        = '' >> "%PS%"
echo $latestRel        = $null >> "%PS%"
echo. >> "%PS%"
echo if (-not $updatesDisabled) { >> "%PS%"
echo     try { >> "%PS%"
echo         $latestRel = Invoke-RestMethod -Uri 'https://api.github.com/repos/TheKaverian/Win2ISO/releases/latest' -Headers @{ 'User-Agent' = 'Win2ISO' } -TimeoutSec 8 -ErrorAction Stop >> "%PS%"
echo         $latestVer = $latestRel.tag_name >> "%PS%"
echo         if ($latestVer -and $latestVer -ne '%VER%') { $updateAvailable = $true } >> "%PS%"
echo     } catch {} >> "%PS%"
echo } >> "%PS%" >> "%PS%"
echo. >> "%PS%"
echo function Invoke-Win2ISOUpdate { >> "%PS%"
echo     $asset = $latestRel.assets ^| Where-Object { $_.name -eq 'Win2ISO.bat' } ^| Select-Object -First 1 >> "%PS%"
echo     if (-not $asset) { >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         Write-Host "  Could not find release asset: Win2ISO.bat" -ForegroundColor Red >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         Write-Host "  Press any key to continue..." -ForegroundColor DarkGray >> "%PS%"
echo         [Console]::ReadKey($true) ^| Out-Null >> "%PS%"
echo         return >> "%PS%"
echo     } >> "%PS%"
echo     Clear-Host >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     Write-Host "  Win2ISO - Windows ISO Downloader" -ForegroundColor Green >> "%PS%"
echo     Write-Host "  =================================" -ForegroundColor DarkGreen >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     Write-Host "  Downloading $latestVer..." -ForegroundColor Yellow >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     $tmpFile  = [IO.Path]::Combine($env:TEMP, 'Win2ISO.bat') >> "%PS%"
echo     $destPath = [IO.Path]::Combine([IO.Path]::GetDirectoryName($selfPath), 'Win2ISO.bat') >> "%PS%"
echo     try { >> "%PS%"
echo         Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $tmpFile -UseBasicParsing >> "%PS%"
echo         $helperPath  = [IO.Path]::Combine($env:TEMP, 'win2iso_updater.bat') >> "%PS%"
echo         $helperLines = '@echo off', 'timeout /t 2 /nobreak ^>nul', "move /y `"$tmpFile`" `"$destPath`"", "start `"`" `"$destPath`"", "del `"$helperPath`"" >> "%PS%"
echo         $helperLines ^| Out-File -FilePath $helperPath -Encoding ASCII >> "%PS%"
echo         Start-Process -FilePath 'cmd.exe' -ArgumentList "/c `"$helperPath`"" >> "%PS%"
echo         Write-Host "  Update downloaded! Restarting Win2ISO..." -ForegroundColor Green >> "%PS%"
echo         Start-Sleep -Seconds 1 >> "%PS%"
echo         exit >> "%PS%"
echo     } catch { >> "%PS%"
echo         Write-Host "  Update failed: $_" -ForegroundColor Red >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         Write-Host "  Press any key to continue..." -ForegroundColor DarkGray >> "%PS%"
echo         [Console]::ReadKey($true) ^| Out-Null >> "%PS%"
echo     } >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"
echo $skipFile = [IO.Path]::Combine($env:ProgramData, 'TheKaverian', 'skip_update.txt') >> "%PS%"
echo if ($updateAvailable -and $latestVer -and -not (Test-Path $skipFile)) { >> "%PS%"
echo     Clear-Host >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     Write-Host "  Win2ISO - Update Available!" -ForegroundColor Green >> "%PS%"
echo     Write-Host "  ===========================" -ForegroundColor DarkGreen >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     Write-Host "  A new version of Win2ISO is available!" -ForegroundColor Yellow >> "%PS%"
echo     Write-Host "  Current : %VER%" -ForegroundColor Gray >> "%PS%"
echo     Write-Host "  Latest  : $latestVer" -ForegroundColor Cyan >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     Write-Host "  [Y] Update Now    [N] Not Now  (won't ask again for this version)" -ForegroundColor Gray >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     [Console]::CursorVisible = $true >> "%PS%"
echo     $upKey = [Console]::ReadKey($true) >> "%PS%"
echo     [Console]::CursorVisible = $false >> "%PS%"
echo     if ($upKey.Key -eq 'Y') { >> "%PS%"
echo         Invoke-Win2ISOUpdate >> "%PS%"
echo     } else { >> "%PS%"
echo         'skip' ^| Out-File -FilePath $skipFile -Encoding ASCII -ErrorAction SilentlyContinue >> "%PS%"
echo     } >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"

rem if you know a better mirror link please send me a message at kaverian61@icloud.com or kaverian@proton.me

rem --- Vista ---
echo $vista_ed  = @('Starter [RTM] - x86 only','Home Basic [RTM]','Home Premium [RTM]','Business [RTM]','Ultimate [RTM]','Starter [SP1] - x86 only','Home Basic [SP1]','Home Premium [SP1]','Business [SP1]','Ultimate [SP1]','Starter [SP2] - x86 only','Home Basic [SP2]','Home Premium [SP2]','Business [SP2]','Ultimate [SP2]','Exit') >> "%PS%"
echo $vista_x86 = @('https://archive.org/download/en_windows_vista_x86_dvd_x12-34293_202010/en_windows_vista_x86_dvd_x12-34293.iso','https://archive.org/download/en_windows_vista_x86_dvd_x12-34293_202010/en_windows_vista_x86_dvd_x12-34293.iso','https://archive.org/download/en_windows_vista_x86_dvd_x12-34293_202010/en_windows_vista_x86_dvd_x12-34293.iso','https://archive.org/download/en_windows_vista_x86_dvd_x12-34293_202010/en_windows_vista_x86_dvd_x12-34293.iso','https://archive.org/download/en_windows_vista_x86_dvd_x12-34293_202010/en_windows_vista_x86_dvd_x12-34293.iso','https://archive.org/download/windows-vista-starter-sp-1/Windows%20Vista%20Starter%20SP1.iso','https://archive.org/download/en_windows_vista_with_service_pack_1_x86_dvd_x14-29594_202010/en_windows_vista_with_service_pack_1_x86_dvd_x14-29594.iso','https://archive.org/download/en_windows_vista_with_service_pack_1_x86_dvd_x14-29594_202010/en_windows_vista_with_service_pack_1_x86_dvd_x14-29594.iso','https://archive.org/download/en_windows_vista_with_service_pack_1_x86_dvd_x14-29594_202010/en_windows_vista_with_service_pack_1_x86_dvd_x14-29594.iso','https://archive.org/download/en_windows_vista_with_service_pack_1_x86_dvd_x14-29594_202010/en_windows_vista_with_service_pack_1_x86_dvd_x14-29594.iso','https://archive.org/download/windows-vista-starter-sp-2/Windows%20Vista%20Starter%20SP2.iso','https://archive.org/download/en_windows_vista_sp2_x86_dvd_342266/en_windows_vista_sp2_x86_dvd_342266.iso','https://archive.org/download/en_windows_vista_sp2_x86_dvd_342266/en_windows_vista_sp2_x86_dvd_342266.iso','https://archive.org/download/en_windows_vista_sp2_x86_dvd_342266/en_windows_vista_sp2_x86_dvd_342266.iso','https://archive.org/download/en_windows_vista_sp2_x86_dvd_342266/en_windows_vista_sp2_x86_dvd_342266.iso') >> "%PS%"
echo $vista_x64 = @('NONE','https://archive.org/download/en_windows_vista_x64_dvd_x12-40712_202010/en_windows_vista_x64_dvd_x12-40712.iso','https://archive.org/download/en_windows_vista_x64_dvd_x12-40712_202010/en_windows_vista_x64_dvd_x12-40712.iso','https://archive.org/download/en_windows_vista_x64_dvd_x12-40712_202010/en_windows_vista_x64_dvd_x12-40712.iso','https://archive.org/download/en_windows_vista_x64_dvd_x12-40712_202010/en_windows_vista_x64_dvd_x12-40712.iso','NONE','https://archive.org/download/en_windows_vista_with_service_pack_1_x64_dvd_x14-29595_202010/en_windows_vista_with_service_pack_1_x64_dvd_x14-29595.iso','https://archive.org/download/en_windows_vista_with_service_pack_1_x64_dvd_x14-29595_202010/en_windows_vista_with_service_pack_1_x64_dvd_x14-29595.iso','https://archive.org/download/en_windows_vista_with_service_pack_1_x64_dvd_x14-29595_202010/en_windows_vista_with_service_pack_1_x64_dvd_x14-29595.iso','https://archive.org/download/en_windows_vista_with_service_pack_1_x64_dvd_x14-29595_202010/en_windows_vista_with_service_pack_1_x64_dvd_x14-29595.iso','NONE','https://archive.org/download/en_windows_vista_sp2_x64_dvd_342267_202010/en_windows_vista_sp2_x64_dvd_342267.iso','https://archive.org/download/en_windows_vista_sp2_x64_dvd_342267_202010/en_windows_vista_sp2_x64_dvd_342267.iso','https://archive.org/download/en_windows_vista_sp2_x64_dvd_342267_202010/en_windows_vista_sp2_x64_dvd_342267.iso','https://archive.org/download/en_windows_vista_sp2_x64_dvd_342267_202010/en_windows_vista_sp2_x64_dvd_342267.iso') >> "%PS%"
echo. >> "%PS%"

rem --- Windows 7 ---
echo $win7_ed   = @('Starter [RTM] - x86 only','Home Premium [RTM] - x64 is Dell OEM','Professional [RTM]','Ultimate [RTM]','Home Premium [SP1]','Professional [SP1]','Ultimate [SP1]','All-In-One [SP1]','Exit') >> "%PS%"
echo $win7_x86  = @('https://archive.org/download/windows_7_starter_n_x86_rtm_english/en_windows_7_starter_n_x86_dvd_x16-15928.iso','https://archive.org/download/Windows7HomePremiumRTMx86/Windows%207%20Home%20Premium%20RTM%20%28GRMCHPFREO_EN_DVD%29.iso','https://archive.org/download/Win_7_RTM_Pro_X86/en_windows_7_professional_x86_dvd_x15-65804.iso','https://archive.org/download/en_windows_7_ultimate_x86_dvd_x15-65921_201902/en_windows_7_ultimate_x86_dvd_x15-65921.iso','https://archive.org/download/windows-7-home-prem-english/Win7_HomePrem_SP1_English_x32.iso','https://archive.org/download/win-7-pro-sp1-english/Win7_Pro_SP1_English_x32.iso','https://archive.org/download/win-7-ult-sp1-english/Win7_Ult_SP1_English_x32.iso','https://archive.org/download/windows-7-aio-sp-1/Windows%207%20AIO%20SP1.ISO') >> "%PS%"
echo $win7_x64  = @('NONE','https://archive.org/download/Windows7HomePremiumRTMx64DellOEM/Dell_Windows_7_Home_Premium_RTM_x64.iso','https://archive.org/download/Win7ProRTMx64/Windows%207%20Professional%20RTM%20x64%20%28Enu%29.iso','https://archive.org/download/Windows7UltimateRTMx64/en_windows_7_ultimate_x64_dvd_x15-65922.iso','https://archive.org/download/windows-7-home-prem-english/Win7_HomePrem_SP1_English_x64.iso','https://archive.org/download/win-7-pro-sp1-english/Win7_Pro_SP1_English_x64.iso','https://archive.org/download/win-7-ult-sp1-english/Win7_Ult_SP1_English_x64.iso','https://archive.org/download/windows-7-all-in-one/Windows_7_All_In_One.ISO') >> "%PS%"
echo. >> "%PS%"

rem --- Windows 8 / 8.1 ---
echo $win8_ed   = @('Windows 8 [RTM]','Windows 8 Pro [RTM]','Windows 8.1 [RTM]','Windows 8.1 Pro [RTM]','Windows 8.1 [Update 1]','Windows 8.1 Pro [Update 1]','Windows 8.1 Enterprise [Update 1]','Windows 8.1 AIO [Update 1]','Exit') >> "%PS%"
echo $win8_x86  = @('https://archive.org/download/Windows-EIGHT-Collection/en_windows_8_debug_checked_build_x64_dvd_917558.iso','https://archive.org/download/Windows-EIGHT-Collection/en_windows_8_pro_vl_x86_dvd_917830.iso','https://archive.org/download/windows-8.1-msdn-iso-files-en-de-ru-tr-x86-x64/tr_windows_8_1_x86_dvd_2707500.iso','https://archive.org/download/windows-8.1-msdn-iso-files-en-de-ru-tr-x86-x64/tr_windows_8_1_x86_dvd_2707500.iso','https://archive.org/download/win-8.1/Win8.1_EnglishInternational_x32.iso','https://archive.org/download/win-8.1/Win8.1_EnglishInternational_x32.iso','https://archive.org/download/win-8.1-english-data-64-data-86/Win8.1_English_x32.iso','https://archive.org/download/win-8.1-english-data-64-data-86/Win8.1_English_x32.iso') >> "%PS%"
echo $win8_x64  = @('https://archive.org/download/Windows-EIGHT-Collection/en_windows_8_debug_checked_build_x64_dvd_917558.iso','https://archive.org/download/Windows-EIGHT-Collection/en_windows_8_n_x64_dvd_916091.iso','https://archive.org/download/windows-8.1-msdn-iso-files-en-de-ru-tr-x86-x64/tr_windows_8_1_x86_dvd_2707500.iso','https://archive.org/download/windows-8.1-msdn-iso-files-en-de-ru-tr-x86-x64/tr_windows_8_1_x86_dvd_2707500.iso','https://archive.org/download/win-8.1/Win8.1_EnglishInternational_x64.iso','https://archive.org/download/win-8.1/Win8.1_EnglishInternational_x64.iso','https://archive.org/download/win-8.1-english-data-64-data-86/Win8.1_English_x64.iso','https://archive.org/download/Win81AIOx64UpdatedJune2019/W81X64.AIO.ENU.JUN2019.iso') >> "%PS%"
echo. >> "%PS%"

rem --- Windows 10 ---
echo $win10_ed  = @('Windows 10 Home 1507','Windows 10 Pro 1507','Windows 10 Home 1511','Windows 10 Pro 1511','Windows 10 Home 1607','Windows 10 Pro 1607','Windows 10 Home 1703','Windows 10 Pro 1703','Windows 10 Home 1709','Windows 10 Pro 1709','Windows 10 Home 1803','Windows 10 Pro 1803','Windows 10 Home 1809','Windows 10 Pro 1809','Windows 10 Home 1903','Windows 10 Pro 1903','Windows 10 Home 2004','Windows 10 Pro 2004','Windows 10 Home 20H2','Windows 10 Pro 20H2','Windows 10 Home 21H1','Windows 10 Pro 21H1','Windows 10 Home 21H2','Windows 10 Pro 21H2','Windows 10 Home 22H2','Windows 10 Pro 22H2','Exit') >> "%PS%"
echo $win10_x86 = @('https://archive.org/download/windows-10-1507-home-and-pro/Win10_EnglishInternational_x32.iso','https://archive.org/download/windows-10-1507-home-and-pro/Win10_EnglishInternational_x32.iso','https://archive.org/download/win10-1511/Win10_1511_EnglishInternational_x32.iso','https://archive.org/download/win10-1511/Win10_1511_EnglishInternational_x32.iso','https://archive.org/download/win10-1607/Win10_1607_EnglishInternational_x32.iso','https://archive.org/download/win10-1607/Win10_1607_EnglishInternational_x32.iso','https://archive.org/download/Windows-10-1703-french/413%20June%202017/en_windows_10_multiple_editions_version_1703_updated_june_2017_x86_dvd_10725453.iso','https://archive.org/download/Windows-10-1703-french/015%20March%202017/English/SW_DVD5_Win_Pro_10_1703_32BIT_English_MLF_X21-36725.ISO','https://archive.org/download/fr_windows_10_multi-edition_vl_version_1709_updated_sept_2017_x86_x64/015%20September%202017/en_windows_10_multi-edition_version_1709_updated_sept_2017_x86_dvd_100090818.iso','https://archive.org/download/fr_windows_10_multi-edition_vl_version_1709_updated_sept_2017_x86_x64/015%20September%202017/en_windows_10_multi-edition_version_1709_updated_sept_2017_x86_dvd_100090818.iso','https://archive.org/download/fr_windows_10_business_editions_version_1803_updated_march_2018_x86_x64/0112%20July%202018/en_windows_10_consumer_edition_version_1803_updated_jul_2018_x86_dvd_12711391.iso','https://archive.org/download/fr_windows_10_business_editions_version_1803_updated_march_2018_x86_x64/0112%20July%202018/en_windows_10_consumer_edition_version_1803_updated_jul_2018_x86_dvd_12711391.iso','https://archive.org/download/windows-10-1809-frnehc/0107-september_2018/en_windows_10_consumer_edition_version_1809_updated_sept_2018_x86_dvd_c5960600.iso','https://archive.org/download/windows-10-1809-frnehc/0107-september_2018/en_windows_10_consumer_edition_version_1809_updated_sept_2018_x86_dvd_c5960600.iso','https://archive.org/download/windows-10-1903-french/0175-June_2019/en_windows_10_consumer_edition_version_1903_updated_june_2019_x86_dvd_d075e11d.iso','https://archive.org/download/windows-10-1903-french/0175-June_2019/en_windows_10_consumer_edition_version_1903_updated_june_2019_x86_dvd_d075e11d.iso','https://archive.org/download/windows-10-2004-home-pro-english-data-86/Windows%2010%202004%20Home-Pro%20English%20x86.iso','https://archive.org/download/windows-10-2004-home-pro-english-data-86/Windows%2010%202004%20Home-Pro%20English%20x86.iso','https://archive.org/download/fr_windows_10_business_editions_version_20h2_x86_x64/0508/en_windows_10_consumer_editions_version_20h2_x86_dvd_ea9a9e3f.iso','https://archive.org/download/fr_windows_10_business_editions_version_20h2_x86_x64/0508/en_windows_10_consumer_editions_version_20h2_x86_dvd_ea9a9e3f.iso','https://archive.org/download/Windows10-21h1-french/0928/en_windows_10_consumer_editions_version_21h1_x86_dvd_68cee121.iso','https://archive.org/download/Windows10-21h1-french/0928/en_windows_10_consumer_editions_version_21h1_x86_dvd_68cee121.iso','https://archive.org/download/fr-fr_windows_10_business_editions_version_21h2_x86_x64/1288/en-us_windows_10_consumer_editions_version_21h2_x86_dvd_31755f1b.iso','https://archive.org/download/fr-fr_windows_10_business_editions_version_21h2_x86_x64/1288/en-us_windows_10_consumer_editions_version_21h2_x86_dvd_31755f1b.iso','https://archive.org/download/en-us_windows_10_consumer_editions_version_22h2_x86_dvd_90883feb/en-us_windows_10_consumer_editions_version_22h2_x86_dvd_90883feb.iso','https://archive.org/download/en-us_windows_10_consumer_editions_version_22h2_x86_dvd_90883feb/en-us_windows_10_consumer_editions_version_22h2_x86_dvd_90883feb.iso') >> "%PS%"
echo $win10_x64 = @('https://archive.org/download/windows-10-1507-home-and-pro/Win10_EnglishInternational_x64.iso','https://archive.org/download/windows-10-1507-home-and-pro/Win10_EnglishInternational_x64.iso','https://archive.org/download/win10-1511/Win10_1511_EnglishInternational_x64.iso','https://archive.org/download/win10-1511/Win10_1511_EnglishInternational_x64.iso','https://archive.org/download/win10-1607/Win10_1607_EnglishInternational_x64.iso','https://archive.org/download/win10-1607/Win10_1607_EnglishInternational_x64.iso','https://archive.org/download/Windows-10-1703-french/413%20June%202017/en_windows_10_multiple_editions_version_1703_updated_june_2017_x64_dvd_10725021.iso','https://archive.org/download/Windows-10-1703-french/413%20June%202017/en_windows_10_multiple_editions_version_1703_updated_june_2017_x64_dvd_10725021.iso','https://archive.org/download/fr_windows_10_multi-edition_vl_version_1709_updated_sept_2017_x86_x64/015%20September%202017/en_windows_10_multi-edition_version_1709_updated_sept_2017_x64_dvd_100090817.iso','https://archive.org/download/fr_windows_10_multi-edition_vl_version_1709_updated_sept_2017_x86_x64/015%20September%202017/en_windows_10_multi-edition_version_1709_updated_sept_2017_x64_dvd_100090817.iso','https://archive.org/download/win101803englishx64/Win10_1803_English_x64.iso','https://archive.org/download/win101803englishx64/Win10_1803_English_x64.iso','https://archive.org/download/windows-10-1809-frnehc/0107-september_2018/en_windows_10_consumer_edition_version_1809_updated_sept_2018_x64_dvd_491ea967.iso','https://archive.org/download/windows-10-1809-frnehc/0107-september_2018/en_windows_10_consumer_edition_version_1809_updated_sept_2018_x64_dvd_491ea967.iso','https://archive.org/download/windows-10-1903-french/0175-June_2019/en_windows_10_consumer_edition_version_1903_updated_june_2019_x64_dvd_8d122c90.iso','https://archive.org/download/windows-10-1903-french/0175-June_2019/en_windows_10_consumer_edition_version_1903_updated_june_2019_x64_dvd_8d122c90.iso','https://archive.org/download/win-10-2004-english-data-64_202010/Win10_2004_English_x64.iso','https://archive.org/download/win-10-2004-english-data-64_202010/Win10_2004_English_x64.iso','https://archive.org/download/win-10-20-h2-v2-english-data-64_20210429/Win10_20H2_v2_English_x64.iso','https://archive.org/download/win-10-20-h2-v2-english-data-64_20210429/Win10_20H2_v2_English_x64.iso','https://archive.org/download/Windows10-21h1-french/0928/en_windows_10_consumer_editions_version_21h1_x64_dvd_540c0dd4.iso','https://archive.org/download/Windows10-21h1-french/0928/en_windows_10_consumer_editions_version_21h1_x64_dvd_540c0dd4.iso','https://archive.org/download/fr-fr_windows_10_business_editions_version_21h2_x86_x64/1288/en-us_windows_10_consumer_editions_version_21h2_x64_dvd_6cfdb144.iso','https://archive.org/download/fr-fr_windows_10_business_editions_version_21h2_x86_x64/1288/en-us_windows_10_consumer_editions_version_21h2_x64_dvd_6cfdb144.iso','https://archive.org/download/en-us_windows_10_consumer_editions_version_22h2_updated_feb_2023_x64_dvd_c29e4bb3/en-us_windows_10_consumer_editions_version_22h2_updated_feb_2023_x64_dvd_c29e4bb3.iso','https://archive.org/download/en-us_windows_10_consumer_editions_version_22h2_updated_feb_2023_x64_dvd_c29e4bb3/en-us_windows_10_consumer_editions_version_22h2_updated_feb_2023_x64_dvd_c29e4bb3.iso') >> "%PS%"
echo. >> "%PS%"

rem --- Windows 11 ---
rem TODO: find actual skig archive placeholders 
echo $win11_ed  = @('21H2 - Initial Release (Oct 2021)','22H2 - 2022 Update','23H2 - 2023 Update','24H2 - 2024 Update','IoT LTSC 2024','Exit') >> "%PS%"
echo $win11_x64 = @('https://PLACEHOLDER/win11_21h2_x64.iso','https://PLACEHOLDER/win11_22h2_x64.iso','https://PLACEHOLDER/win11_23h2_x64.iso','https://PLACEHOLDER/win11_24h2_x64.iso','https://PLACEHOLDER/win11_ltsc24_x64.iso') >> "%PS%"
echo. >> "%PS%"

rem --- Windows Server ---
rem TODO: fill in these PLACEHOLDERs
echo $winserver_ed  = @('Windows Server 2008','Windows Server 2008 R2','Windows Server 2012','Windows Server 2012 R2','Windows Server 2016 - x64 only','Windows Server 2019 - x64 only','Windows Server 2022 - x64 only','Windows Server 2025 - x64 only','Exit') >> "%PS%"
echo $winserver_x86 = @('https://PLACEHOLDER/winserver_2008_x86.iso','https://PLACEHOLDER/winserver_2008r2_x86.iso','https://PLACEHOLDER/winserver_2012_x86.iso','https://PLACEHOLDER/winserver_2012r2_x86.iso','NONE','NONE','NONE','NONE') >> "%PS%"
echo $winserver_x64 = @('https://PLACEHOLDER/winserver_2008_x64.iso','https://PLACEHOLDER/winserver_2008r2_x64.iso','https://PLACEHOLDER/winserver_2012_x64.iso','https://PLACEHOLDER/winserver_2012r2_x64.iso','https://PLACEHOLDER/winserver_2016_x64.iso','https://PLACEHOLDER/winserver_2019_x64.iso','https://PLACEHOLDER/winserver_2022_x64.iso','https://PLACEHOLDER/winserver_2025_x64.iso') >> "%PS%"
echo. >> "%PS%"

rem --- Windows LTSC ---
rem TODO: fill in these PLACEHOLDERs
echo $winltsc_ed  = @('Windows 7 Enterprise','Windows 10 Enterprise LTSC 2015 - x64 only','Windows 10 Enterprise LTSC 2016 - x64 only','Windows 10 Enterprise LTSC 2019 - x64 only','Windows 10 Enterprise LTSC 2021 - x64 only','Windows 11 Enterprise LTSC 2024 - x64 only','Exit') >> "%PS%"
echo $winltsc_x86 = @('https://PLACEHOLDER/win7_ent_x86.iso','NONE','NONE','NONE','NONE','NONE') >> "%PS%"
echo $winltsc_x64 = @('https://PLACEHOLDER/win7_ent_x64.iso','https://PLACEHOLDER/win10_ltsc_2015_x64.iso','https://PLACEHOLDER/win10_ltsc_2016_x64.iso','https://PLACEHOLDER/win10_ltsc_2019_x64.iso','https://PLACEHOLDER/win10_ltsc_2021_x64.iso','https://PLACEHOLDER/win11_ltsc_2024_x64.iso') >> "%PS%"
echo. >> "%PS%"

rem OS LIST; EDIT IF NECCESSARY
echo $os_names = @('Windows Vista','Windows 7','Windows 8 / 8.1','Windows 10','Windows 11','Windows Server','Windows LTSC','More...') >> "%PS%"
echo. >> "%PS%"
echo function Format-Bytes2($b) { >> "%PS%"
echo     if ($b -ge 1073741824) { return ('{0:N2} GB' -f ($b / 1073741824)) } >> "%PS%"
echo     if ($b -ge 1048576)    { return ('{0:N2} MB' -f ($b / 1048576)) } >> "%PS%"
echo     if ($b -ge 1024)       { return ('{0:N2} KB' -f ($b / 1024)) } >> "%PS%"
echo     return "$b B" >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"
echo while ($true) { >> "%PS%"
echo     if (-not $updatesDisabled) { >> "%PS%"
echo         $updateLabel  = if ($updateAvailable) { "[!] Update to $latestVer available - click to install" } else { "Check for Updates  (current: %VER%)" } >> "%PS%"
echo         $displayNames = @($updateLabel) + $os_names >> "%PS%"
echo     } else { >> "%PS%"
echo         $displayNames = $os_names >> "%PS%"
echo     } >> "%PS%"
echo     $o = Show-Menu 'Select a Windows version' $displayNames 'Exit' >> "%PS%"
echo     if ($o -eq -1) { >> "%PS%"
echo         Clear-Host >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         Write-Host "  Win2ISO - Windows ISO Downloader" -ForegroundColor Green >> "%PS%"
echo         Write-Host "  =================================" -ForegroundColor DarkGreen >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         Write-Host "  Are you sure you want to exit?" -ForegroundColor Yellow >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         Write-Host "  [Y] Yes - Exit    [N] No - Back to Menu" -ForegroundColor Gray >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         $exitKey = [Console]::ReadKey($true) >> "%PS%"
echo         if ($exitKey.Key -eq 'Y' -or $exitKey.Key -eq 'Escape' -or $exitKey.Key -eq 'Backspace') { break } >> "%PS%"
echo         continue >> "%PS%"
echo     } >> "%PS%"
echo. >> "%PS%"
echo     if (-not $updatesDisabled -and $o -eq 0) { >> "%PS%"
echo         if ($updateAvailable) { >> "%PS%"
echo             Invoke-Win2ISOUpdate >> "%PS%"
echo         } else { >> "%PS%"
echo             Clear-Host >> "%PS%"
echo             Write-Host "" >> "%PS%"
echo             Write-Host "  Win2ISO - Windows ISO Downloader" -ForegroundColor Green >> "%PS%"
echo             Write-Host "  =================================" -ForegroundColor DarkGreen >> "%PS%"
echo             Write-Host "" >> "%PS%"
echo             Write-Host "  You are already on the latest version (%VER%)." -ForegroundColor Green >> "%PS%"
echo             Write-Host "" >> "%PS%"
echo             Write-Host "  Press any key to continue..." -ForegroundColor DarkGray >> "%PS%"
echo             [Console]::ReadKey($true) ^| Out-Null >> "%PS%"
echo         } >> "%PS%"
echo         continue >> "%PS%"
echo     } >> "%PS%"
echo     $osIdx = if (-not $updatesDisabled) { $o - 1 } else { $o } >> "%PS%"
echo. >> "%PS%"
echo     if ($osIdx -eq 7) { >> "%PS%"
echo         while ($true) { >> "%PS%"
echo             $updLabel    = if ($updatesDisabled) { 'Enable Updates' } else { 'Disable Updates' } >> "%PS%"
echo             $moreItems = @('About Win2ISO','Win2ISO on GitHub','Credits','Legal','License',$updLabel,'Custom URL Download','Back') >> "%PS%"
echo             $m = Show-Menu 'More' $moreItems >> "%PS%"
echo             if ($m -eq -1 -or $m -eq 7) { break } >> "%PS%"
echo             switch ($m) { >> "%PS%"
echo                 0 { >> "%PS%"
echo                     $esc = [char]27 >> "%PS%"
echo                     $aboutLines = @( >> "%PS%"
echo                         '  +------------------------------------------------------------------------+', >> "%PS%"
echo                         '  ^|                          ~~ ABOUT Win2ISO ~~                           ^|', >> "%PS%"
echo                         '  +------------------------------------------------------------------------+', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  Win2ISO is a free, open-source Windows ISO downloader.                ^|', >> "%PS%"
echo                         '  ^|  It''s purpose is to let you easily download genuine Windows ISOs      ^|', >> "%PS%"
echo                         '  ^|  from trusted public archive sources - no addons, no gimmicks,         ^|', >> "%PS%"
echo                         '  ^|  and no bloatware. Just pick your version and go. It runs in a         ^|', >> "%PS%"
echo                         '  ^|  Windows CLI enviroment, such as CMD Prompt.                           ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  +------------------------------------------------------------------------+', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  SUPPORTED OPERATING SYSTEMS                                           ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  Windows Vista                                                         ^|', >> "%PS%"
echo                         '  ^|  Windows 7                                                             ^|', >> "%PS%"
echo                         '  ^|  Windows 8 / 8.1                                                       ^|', >> "%PS%"
echo                         '  ^|  Windows 10  (multiple editions)                                       ^|', >> "%PS%"
echo                         '  ^|  Windows 11  (multiple editions)                                       ^|', >> "%PS%"
echo                         '  ^|  Windows Server  (2008 through 2025)                                   ^|', >> "%PS%"
echo                         '  ^|  Windows LTSC editions                                                 ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  +------------------------------------------------------------------------+', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  HOW TO USE                                                            ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  1. Select a Windows version from the main menu                        ^|', >> "%PS%"
echo                         '  ^|  2. Choose an edition (Home, Pro, etc.)                                ^|', >> "%PS%"
echo                         '  ^|  3. Pick your architecture (x86 or x64)                                ^|', >> "%PS%"
echo                         '  ^|  4. Confirm the download                                               ^|', >> "%PS%"
echo                         '  ^|  5. Wait for cURL to fetch the ISO                                     ^|', >> "%PS%"
echo                         '  ^|  6. Find your .iso file in the same folder as Win2ISO                  ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  +------------------------------------------------------------------------+', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  REQUIREMENTS                                                          ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  - Windows (any version with PowerShell 5+)                            ^|', >> "%PS%"
echo                         '  ^|  - A stable internet connection                                        ^|', >> "%PS%"
echo                         '  ^|  - Enough free disk space for the ISO  (2-6 GB typical)                ^|', >> "%PS%"
echo                         '  ^|  - cURL  (built into Windows 10/11; bundled for older versions)        ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  +------------------------------------------------------------------------+', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         "  ^|  Version  :  %VER%                                                    ^|", >> "%PS%"
echo                         "  ^|  Source   :  $esc]8;;https://github.com/TheKaverian/Win2ISO$esc\github.com/TheKaverian/Win2ISO$esc]8;;$esc\                   ^|", >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  +------------------------------------------------------------------------+' >> "%PS%"
echo                     ) >> "%PS%"
echo                     $aboutScroll = 0 >> "%PS%"
echo                     $aboutVisible = 14 >> "%PS%"
echo                     $aboutTotal = $aboutLines.Count >> "%PS%"
echo                     while ($true) { >> "%PS%"
echo                         Clear-Host >> "%PS%"
echo                         Write-Host "" >> "%PS%"
echo                         Write-Host "  Win2ISO - Windows ISO Downloader" -ForegroundColor Green >> "%PS%"
echo                         Write-Host "  =================================" -ForegroundColor DarkGreen >> "%PS%"
echo                         $aEnd = [Math]::Min($aboutScroll + $aboutVisible, $aboutTotal) >> "%PS%"
echo                         for ($ai = $aboutScroll; $ai -lt $aEnd; $ai++) { >> "%PS%"
echo                             $aln = $aboutLines[$ai] >> "%PS%"
echo                             if     ($aln.Contains('+-'))                                { $ac='DarkGray' } >> "%PS%"
echo                             elseif ($aln.Contains('~~ ABOUT'))                          { $ac='Yellow'   } >> "%PS%"
echo                             elseif ($aln.Contains('SUPPORTED') -or $aln.Contains('HOW TO USE') -or $aln.Contains('REQUIREMENTS')) { $ac='Cyan' } >> "%PS%"
echo                             elseif ($aln.Contains('Version') -or $aln.Contains('Source')) { $ac='DarkGreen' } >> "%PS%"
echo                             elseif ($aln.Contains('  ^|  -') -or $aln -match '\d\.') { $ac='Gray' } >> "%PS%"
echo                             else                                                         { $ac='White'    } >> "%PS%"
echo                             Write-Host $aln -ForegroundColor $ac >> "%PS%"
echo                         } >> "%PS%"
echo                         $aCanUp   = $aboutScroll -gt 0 >> "%PS%"
echo                         $aCanDown = ($aboutScroll + $aboutVisible) -lt $aboutTotal >> "%PS%"
echo                         $aPct = if ($aboutTotal -le $aboutVisible) { 100 } else { [int](($aboutScroll / ($aboutTotal - $aboutVisible)) * 100) } >> "%PS%"
echo                         Write-Host "" >> "%PS%"
echo                         Write-Host "  [Up/Down] [PgUp/PgDn] [Home/End]   [Esc] Back   $aPct%%" -ForegroundColor DarkGray >> "%PS%"
echo                         while ([Console]::KeyAvailable) { [Console]::ReadKey($true) ^| Out-Null } >> "%PS%"
echo                         $ack = [Console]::ReadKey($true) >> "%PS%"
echo                         if ($ack.Key -eq 'Escape')                          { break } >> "%PS%"
echo                         if ($ack.Key -eq 'UpArrow'   -and $aCanUp)    { $aboutScroll-- } >> "%PS%"
echo                         if ($ack.Key -eq 'DownArrow' -and $aCanDown)  { $aboutScroll++ } >> "%PS%"
echo                         if ($ack.Key -eq 'PageUp')   { $aboutScroll = [Math]::Max(0, $aboutScroll - $aboutVisible) } >> "%PS%"
echo                         if ($ack.Key -eq 'PageDown') { $aboutScroll = [Math]::Min($aboutTotal - $aboutVisible, $aboutScroll + $aboutVisible) } >> "%PS%"
echo                         if ($ack.Key -eq 'Home')     { $aboutScroll = 0 } >> "%PS%"
echo                         if ($ack.Key -eq 'End')      { $aboutScroll = [Math]::Max(0, $aboutTotal - $aboutVisible) } >> "%PS%"
echo                     } >> "%PS%"
echo                 } >> "%PS%"
echo                 1 { >> "%PS%"
echo                     Start-Process 'https://github.com/TheKaverian/Win2ISO' >> "%PS%"
echo                     Clear-Host >> "%PS%"
echo                     Write-Host "" >> "%PS%"
echo                     Write-Host "  Opened Win2ISO on GitHub in your browser!" -ForegroundColor Green >> "%PS%"
echo                     Write-Host "" >> "%PS%"
echo                     Write-Host "  Press any key to continue..." -ForegroundColor DarkGray >> "%PS%"
echo                     [Console]::ReadKey($true) ^| Out-Null >> "%PS%"
echo                 } >> "%PS%"
echo                 2 { >> "%PS%"
echo                     $esc = [char]27 >> "%PS%"
echo                     $credLines = @( >> "%PS%"
echo                         '  +------------------------------------------------------------------------+', >> "%PS%"
echo                         '  ^|                             ~~ CREDITS ~~                              ^|', >> "%PS%"
echo                         '  +------------------------------------------------------------------------+', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  DEVELOPERS                                                            ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  kaverian                                        [Lead Developer]      ^|', >> "%PS%"
echo                         "  ^|    GitHub :  $esc]8;;https://github.com/TheKaverian$esc\github.com/TheKaverian$esc]8;;$esc\                                   ^|", >> "%PS%"
echo                         "  ^|    Email  :  $esc]8;;mailto:kaverian61@icloud.com$esc\kaverian61@icloud.com$esc]8;;$esc\                                    ^|", >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  chicken                                         [Contributor]         ^|', >> "%PS%"
echo                         "  ^|    GitHub :  $esc]8;;https://github.com/Wild-Chicken$esc\github.com/Wild-Chicken$esc]8;;$esc\                                   ^|", >> "%PS%"
echo                         "  ^|    Email  :  $esc]8;;mailto:postmaster@nuggets.pw$esc\postmaster@nuggets.pw$esc]8;;$esc\                                  ^|", >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  blinx                                            [Designer]           ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  +------------------------------------------------------------------------+', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  BUILT WITH                                                            ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  Language    :  Windows Batch (.bat) + PowerShell                      ^|', >> "%PS%"
echo                         "  ^|  Downloader  :  $esc]8;;https://curl.se$esc\cURL$esc]8;;$esc\  -  free, fast, everywhere                         ^|", >> "%PS%"
echo                         "  ^|  ISO Sources :  $esc]8;;https://archive.org$esc\Internet Archive$esc]8;;$esc\  -  archive.org                    ^|", >> "%PS%"
echo                         '  ^|  Shell       :  PowerShell 5+ (built into modern Windows)              ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  +------------------------------------------------------------------------+', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  ACKNOWLEDGEMENTS                                                      ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  The Internet Archive   for keeping old ISOs alive and accessible      ^|', >> "%PS%"
echo                         '  ^|  Microsoft              for building Windows                           ^|', >> "%PS%"
echo                         '  ^|  The cURL project       for the best download tool ever written        ^|', >> "%PS%"
echo                         '  ^|  PowerShell team        for allowing for complex things on my script   ^|', >> "%PS%"
echo                         '  ^|  Open source community  for the shared knowledge that made this        ^|', >> "%PS%"
echo                         '  ^|  Stack Overflow         for the help aswell                          ^  |', >> "%PS%"
echo                         '  ^|  You                    for using Win2ISO                              ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  +------------------------------------------------------------------------+', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         "  ^|  Win2ISO %VER%              $esc]8;;https://github.com/TheKaverian/Win2ISO$esc\github.com/TheKaverian/Win2ISO$esc]8;;$esc\            ^|", >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  +------------------------------------------------------------------------+' >> "%PS%"
echo                     ) >> "%PS%"
echo                     $credScroll = 0 >> "%PS%"
echo                     $credVisible = 14 >> "%PS%"
echo                     $credTotal = $credLines.Count >> "%PS%"
echo                     while ($true) { >> "%PS%"
echo                         Clear-Host >> "%PS%"
echo                         Write-Host "" >> "%PS%"
echo                         Write-Host "  Win2ISO - Windows ISO Downloader" -ForegroundColor Green >> "%PS%"
echo                         Write-Host "  =================================" -ForegroundColor DarkGreen >> "%PS%"
echo                         $cEnd = [Math]::Min($credScroll + $credVisible, $credTotal) >> "%PS%"
echo                         for ($ci = $credScroll; $ci -lt $cEnd; $ci++) { >> "%PS%"
echo                             $ln = $credLines[$ci] >> "%PS%"
echo                             if     ($ln.Contains('+-'))                                                                                              { $c='DarkGray' } >> "%PS%"
echo                             elseif ($ln.Contains('~~ CREDITS ~~'))                                                                                   { $c='Yellow'   } >> "%PS%"
echo                             elseif ($ln.Contains('DEVELOPERS') -or $ln.Contains('BUILT WITH') -or $ln.Contains('ACKNOWLEDGEMENTS'))                  { $c='Cyan'     } >> "%PS%"
echo                             elseif ($ln.Contains('    GitHub') -or $ln.Contains('    Email'))                                                        { $c='Gray'     } >> "%PS%"
echo                             elseif ($ln.Contains('Win2ISO v'))                                                                                       { $c='DarkGreen'} >> "%PS%"
echo                             else                                                                                                                     { $c='White'    } >> "%PS%"
echo                             Write-Host $ln -ForegroundColor $c >> "%PS%"
echo                         } >> "%PS%"
echo                         $canUp   = $credScroll -gt 0 >> "%PS%"
echo                         $canDown = ($credScroll + $credVisible) -lt $credTotal >> "%PS%"
echo                         $pct = if ($credTotal -le $credVisible) { 100 } else { [int](($credScroll / ($credTotal - $credVisible)) * 100) } >> "%PS%"
echo                         Write-Host "" >> "%PS%"
echo                         Write-Host "  [Up/Down] [PgUp/PgDn] [Home/End]   [Esc] Back   $pct%%" -ForegroundColor DarkGray >> "%PS%"
echo                         while ([Console]::KeyAvailable) { [Console]::ReadKey($true) ^| Out-Null } >> "%PS%"
echo                         $ck = [Console]::ReadKey($true) >> "%PS%"
echo                         if ($ck.Key -eq 'Escape')                         { break } >> "%PS%"
echo                         if ($ck.Key -eq 'UpArrow'   -and $canUp)    { $credScroll-- } >> "%PS%"
echo                         if ($ck.Key -eq 'DownArrow' -and $canDown)  { $credScroll++ } >> "%PS%"
echo                         if ($ck.Key -eq 'PageUp')   { $credScroll = [Math]::Max(0, $credScroll - $credVisible) } >> "%PS%"
echo                         if ($ck.Key -eq 'PageDown') { $credScroll = [Math]::Min($credTotal - $credVisible, $credScroll + $credVisible) } >> "%PS%"
echo                         if ($ck.Key -eq 'Home')     { $credScroll = 0 } >> "%PS%"
echo                         if ($ck.Key -eq 'End')      { $credScroll = [Math]::Max(0, $credTotal - $credVisible) } >> "%PS%"
echo                     } >> "%PS%"
echo                 } >> "%PS%"
echo                 3 { >> "%PS%"
echo                     $legalLines = @( >> "%PS%"
echo                         '  +------------------------------------------------------------------------+', >> "%PS%"
echo                         '  ^|                              ~~ LEGAL ~~                               ^|', >> "%PS%"
echo                         '  +------------------------------------------------------------------------+', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  DISCLAIMER                                                            ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  Win2ISO does not host, store or distribute any ISO Files.             ^|', >> "%PS%"
echo                         '  ^|  All download''s explicitly point towards publically available         ^|', >> "%PS%"
echo                         '  ^|  third-party sources such as the Internet Archive. Win2ISO is          ^|', >> "%PS%"
echo                         '  ^|  merely a convenience tool to support you in your endeavour in         ^|', >> "%PS%"
echo                         '  ^|  finding and downloading these files.                                  ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  Use of this tool is at mine and your own risk.                        ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  +------------------------------------------------------------------------+', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  TRADEMARKS                                                            ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  Windows is a registered trademark of Microsoft Corporation.           ^|', >> "%PS%"
echo                         '  ^|  Win2ISO is not affiliated with, endorsed by, or sponsored by          ^|', >> "%PS%"
echo                         '  ^|  Microsoft in any way.                                                 ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  All other product names, trademarks, and registered trademarks        ^|', >> "%PS%"
echo                         '  ^|  are the property of their respective owners.                          ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  +------------------------------------------------------------------------+', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  LICENSE                                                               ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  Win2ISO is released under the MIT license.                            ^|', >> "%PS%"
echo                         '  ^|  You are free to use, copy, modify, and distribute this software       ^|', >> "%PS%"
echo                         '  ^|  in accordance with the terms of that license.                         ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  The full license text can be viewed from More ^> License.             ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  +------------------------------------------------------------------------+', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  PRIVACY                                                               ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  ^|  Win2ISO does not collect, transmit, or store any personal data.       ^|', >> "%PS%"
echo                         '  ^|  Network requests are made only to download the ISO you select         ^|', >> "%PS%"
echo                         '  ^|  and to test your internet connection.                                 ^|', >> "%PS%"
echo                         '  ^|                                                                        ^|', >> "%PS%"
echo                         '  +------------------------------------------------------------------------+' >> "%PS%"
echo                     ) >> "%PS%"
echo                     $legalScroll = 0 >> "%PS%"
echo                     $legalVisible = 14 >> "%PS%"
echo                     $legalTotal = $legalLines.Count >> "%PS%"
echo                     while ($true) { >> "%PS%"
echo                         Clear-Host >> "%PS%"
echo                         Write-Host "" >> "%PS%"
echo                         Write-Host "  Win2ISO - Windows ISO Downloader" -ForegroundColor Green >> "%PS%"
echo                         Write-Host "  =================================" -ForegroundColor DarkGreen >> "%PS%"
echo                         $lEnd = [Math]::Min($legalScroll + $legalVisible, $legalTotal) >> "%PS%"
echo                         for ($li = $legalScroll; $li -lt $lEnd; $li++) { >> "%PS%"
echo                             $lln = $legalLines[$li] >> "%PS%"
echo                             if     ($lln.Contains('+-'))                                                                                     { $lc='DarkGray' } >> "%PS%"
echo                             elseif ($lln.Contains('~~ LEGAL ~~'))                                                                            { $lc='Yellow'   } >> "%PS%"
echo                             elseif ($lln.Contains('DISCLAIMER') -or $lln.Contains('TRADEMARKS') -or $lln.Contains('LICENSE') -or $lln.Contains('PRIVACY')) { $lc='Cyan' } >> "%PS%"
echo                             elseif ($lln.Contains('Win2ISO does not') -or $lln.Contains('not affiliated') -or $lln.Contains('All download') -or $lln.Contains('Use of this')) { $lc='DarkYellow' } >> "%PS%"
echo                             else                                                                                                             { $lc='White'    } >> "%PS%"
echo                             Write-Host $lln -ForegroundColor $lc >> "%PS%"
echo                         } >> "%PS%"
echo                         $lCanUp   = $legalScroll -gt 0 >> "%PS%"
echo                         $lCanDown = ($legalScroll + $legalVisible) -lt $legalTotal >> "%PS%"
echo                         $lPct = if ($legalTotal -le $legalVisible) { 100 } else { [int](($legalScroll / ($legalTotal - $legalVisible)) * 100) } >> "%PS%"
echo                         Write-Host "" >> "%PS%"
echo                         Write-Host "  [Up/Down] [PgUp/PgDn] [Home/End]   [Esc] Back   $lPct%%" -ForegroundColor DarkGray >> "%PS%"
echo                         while ([Console]::KeyAvailable) { [Console]::ReadKey($true) ^| Out-Null } >> "%PS%"
echo                         $lk = [Console]::ReadKey($true) >> "%PS%"
echo                         if ($lk.Key -eq 'Escape')                          { break } >> "%PS%"
echo                         if ($lk.Key -eq 'UpArrow'   -and $lCanUp)    { $legalScroll-- } >> "%PS%"
echo                         if ($lk.Key -eq 'DownArrow' -and $lCanDown)  { $legalScroll++ } >> "%PS%"
echo                         if ($lk.Key -eq 'PageUp')   { $legalScroll = [Math]::Max(0, $legalScroll - $legalVisible) } >> "%PS%"
echo                         if ($lk.Key -eq 'PageDown') { $legalScroll = [Math]::Min($legalTotal - $legalVisible, $legalScroll + $legalVisible) } >> "%PS%"
echo                         if ($lk.Key -eq 'Home')     { $legalScroll = 0 } >> "%PS%"
echo                         if ($lk.Key -eq 'End')      { $legalScroll = [Math]::Max(0, $legalTotal - $legalVisible) } >> "%PS%"
echo                     } >> "%PS%"
echo                 } >> "%PS%"
echo                 4 { >> "%PS%"
echo                     Clear-Host >> "%PS%"
echo                     Write-Host "" >> "%PS%"
echo                     Write-Host "  Win2ISO - Windows ISO Downloader" -ForegroundColor Green >> "%PS%"
echo                     Write-Host "  =================================" -ForegroundColor DarkGreen >> "%PS%"
echo                     Write-Host "" >> "%PS%"
echo                     Write-Host "  Downloading license..." -ForegroundColor Yellow >> "%PS%"
echo                     $licTmp = [IO.Path]::Combine($env:ProgramData, 'TheKaverian', 'LICENSE.txt') >> "%PS%"
echo                     try { >> "%PS%"
echo                         Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/TheKaverian/Win2ISO/main/other/LICENSE.txt' -OutFile $licTmp -UseBasicParsing >> "%PS%"
echo                         Invoke-Item $licTmp >> "%PS%"
echo                         Write-Host "  License opened in your default viewer." -ForegroundColor Green >> "%PS%"
echo                     } catch { >> "%PS%"
echo                         Write-Host "  Failed to download license: $_" -ForegroundColor Red >> "%PS%"
echo                     } >> "%PS%"
echo                     Write-Host "" >> "%PS%"
echo                     Write-Host "  Press any key to continue..." -ForegroundColor DarkGray >> "%PS%"
echo                     [Console]::ReadKey($true) ^| Out-Null >> "%PS%"
echo                 } >> "%PS%"
echo                 5 { >> "%PS%"
echo                     if ($updatesDisabled) { >> "%PS%"
echo                         Remove-Item $updateDisFlag -ErrorAction SilentlyContinue >> "%PS%"
echo                         $updatesDisabled = $false >> "%PS%"
echo                         Write-Host "" >> "%PS%"
echo                         Write-Host "  Updates enabled." -ForegroundColor Green >> "%PS%"
echo                     } else { >> "%PS%"
echo                         'disabled' ^| Out-File -FilePath $updateDisFlag -Encoding ASCII -ErrorAction SilentlyContinue >> "%PS%"
echo                         $updatesDisabled = $true >> "%PS%"
echo                         $updateAvailable = $false >> "%PS%"
echo                         Write-Host "" >> "%PS%"
echo                         Write-Host "  Updates disabled." -ForegroundColor Yellow >> "%PS%"
echo                     } >> "%PS%"
echo                     Write-Host "" >> "%PS%"
echo                     Write-Host "  Press any key to continue..." -ForegroundColor DarkGray >> "%PS%"
echo                     [Console]::ReadKey($true) ^| Out-Null >> "%PS%"
echo                 } >> "%PS%"
echo                 6 { >> "%PS%"
echo                     Clear-Host >> "%PS%"
echo                     [Console]::CursorVisible = $true >> "%PS%"
echo                     Write-Host '' >> "%PS%"
echo                     Write-Host '  Win2ISO - Custom URL Download' -ForegroundColor Green >> "%PS%"
echo                     Write-Host '  ==============================' -ForegroundColor DarkGreen >> "%PS%"
echo                     Write-Host '' >> "%PS%"
echo                     Write-Host '  Enter the URL to download:' -ForegroundColor Yellow >> "%PS%"
echo                     Write-Host '' >> "%PS%"
echo                     Write-Host '  [Enter] Confirm   [Esc] Back' -ForegroundColor DarkGray >> "%PS%"
echo                     Write-Host '' >> "%PS%"
echo                     Write-Host '  URL: ' -NoNewline >> "%PS%"
echo                     $customUrl = '' >> "%PS%"
echo                     while ($true) { >> "%PS%"
echo                         $ck = [Console]::ReadKey($true) >> "%PS%"
echo                         if ($ck.Key -eq 'Enter') { break } >> "%PS%"
echo                         elseif ($ck.Key -eq 'Escape') { $customUrl = ''; break } >> "%PS%"
echo                         elseif ($ck.Key -eq 'Backspace') { >> "%PS%"
echo                             if ($customUrl.Length -gt 0) { >> "%PS%"
echo                                 $customUrl = $customUrl.Substring(0, $customUrl.Length - 1) >> "%PS%"
echo                                 [Console]::Write([char]8 + ' ' + [char]8) >> "%PS%"
echo                             } >> "%PS%"
echo                         } elseif ($ck.KeyChar -ne [char]0) { >> "%PS%"
echo                             $customUrl += $ck.KeyChar >> "%PS%"
echo                             [Console]::Write($ck.KeyChar) >> "%PS%"
echo                         } >> "%PS%"
echo                     } >> "%PS%"
echo                     Write-Host '' >> "%PS%"
echo                     $customUrl = $customUrl.Trim() >> "%PS%"
echo                     if (-not $customUrl) { >> "%PS%"
echo                         Write-Host '' >> "%PS%"
echo                         Write-Host '  No URL entered. Going back.' -ForegroundColor Red >> "%PS%"
echo                         Start-Sleep -Seconds 1 >> "%PS%"
echo                         [Console]::CursorVisible = $false >> "%PS%"
echo                     } else { >> "%PS%"
echo                         Add-Type -AssemblyName System.Windows.Forms >> "%PS%"
echo                         $fb = New-Object System.Windows.Forms.FolderBrowserDialog >> "%PS%"
echo                         $fb.Description = 'Select folder to save download' >> "%PS%"
echo                         $fb.ShowNewFolderButton = $true >> "%PS%"
echo                         if ($fb.ShowDialog() -ne 'OK') { >> "%PS%"
echo                             Write-Host '' >> "%PS%"
echo                             Write-Host '  No folder selected. Going back.' -ForegroundColor Yellow >> "%PS%"
echo                             Start-Sleep -Seconds 1 >> "%PS%"
echo                             [Console]::CursorVisible = $false >> "%PS%"
echo                         } else { >> "%PS%"
echo                             $customDir   = $fb.SelectedPath >> "%PS%"
echo                             $customFname = [IO.Path]::GetFileName(([uri]$customUrl).LocalPath) >> "%PS%"
echo                             if (-not $customFname) { $customFname = 'download' } >> "%PS%"
echo                             $customOut   = [IO.Path]::Combine($customDir, $customFname) >> "%PS%"
echo                             $customTotal = 0 >> "%PS%"
echo                             try { >> "%PS%"
echo                                 $hreq = [System.Net.WebRequest]::Create($customUrl) >> "%PS%"
echo                                 $hreq.Method = 'HEAD'; $hreq.Timeout = 8000 >> "%PS%"
echo                                 $hrs = $hreq.GetResponse() >> "%PS%"
echo                                 $customTotal = $hrs.ContentLength >> "%PS%"
echo                                 $hrs.Close() >> "%PS%"
echo                             } catch {} >> "%PS%"
echo                             $cp = New-Object Diagnostics.ProcessStartInfo >> "%PS%"
echo                             $cp.FileName = $curl >> "%PS%"
echo                             $cp.Arguments = "--silent --location --retry 3 --output `"$customOut`" `"$customUrl`"" >> "%PS%"
echo                             $cp.UseShellExecute = $false >> "%PS%"
echo                             $cproc = [Diagnostics.Process]::Start($cp) >> "%PS%"
echo                             $cStart = [DateTime]::Now >> "%PS%"
echo                             $cLast = 0; $cLastTime = $cStart; $cSpeed = 0 >> "%PS%"
echo                             Clear-Host >> "%PS%"
echo                             [Console]::CursorVisible = $false >> "%PS%"
echo                             $cSzLbl = if ($customTotal -gt 0) { Format-Bytes2 $customTotal } else { 'Unknown' } >> "%PS%"
echo                             Write-Host '' >> "%PS%"
echo                             Write-Host '  Win2ISO - Custom URL Download' -ForegroundColor Green >> "%PS%"
echo                             Write-Host '  ==============================' -ForegroundColor DarkGreen >> "%PS%"
echo                             Write-Host '' >> "%PS%"
echo                             Write-Host "  URL    : $customUrl" -ForegroundColor DarkGray >> "%PS%"
echo                             Write-Host "  Saving : $customOut" -ForegroundColor DarkGray >> "%PS%"
echo                             Write-Host "  Size   : $cSzLbl" -ForegroundColor DarkGray >> "%PS%"
echo                             Write-Host '' >> "%PS%"
echo                             Write-Host '  Keep this window open! Press [Esc] to cancel.' -ForegroundColor Red >> "%PS%"
echo                             Write-Host '' >> "%PS%"
echo                             $cRow = [Console]::CursorTop >> "%PS%"
echo                             Write-Host ('  ' + ' '.PadRight(76)) >> "%PS%"
echo                             Write-Host ('  ' + ' '.PadRight(76)) >> "%PS%"
echo                             Write-Host ('  ' + ' '.PadRight(76)) >> "%PS%"
echo                             Write-Host ('  ' + ' '.PadRight(76)) >> "%PS%"
echo                             $cCancelled = $false >> "%PS%"
echo                             while (-not $cproc.HasExited) { >> "%PS%"
echo                                 $cNow = [DateTime]::Now >> "%PS%"
echo                                 $cCur = 0 >> "%PS%"
echo                                 if (Test-Path $customOut) { try { $cCur = (Get-Item $customOut -ErrorAction Stop).Length } catch {} } >> "%PS%"
echo                                 $cSE = ($cNow - $cLastTime).TotalSeconds >> "%PS%"
echo                                 if ($cSE -ge 1) { $cSpeed = ($cCur - $cLast) / $cSE; $cLast = $cCur; $cLastTime = $cNow } >> "%PS%"
echo                                 $cPct = if ($customTotal -gt 0) { [Math]::Min(100,[int](($cCur / $customTotal) * 100)) } else { -1 } >> "%PS%"
echo                                 $cEta = 'Calculating...' >> "%PS%"
echo                                 if ($cSpeed -gt 0 -and $customTotal -gt 0 -and $cCur -lt $customTotal) { >> "%PS%"
echo                                     $es = [int](($customTotal - $cCur) / $cSpeed) >> "%PS%"
echo                                     $eh = [int]($es / 3600); $em = [int](($es %% 3600) / 60); $esec = $es %% 60 >> "%PS%"
echo                                     if     ($eh -gt 0) { $cEta = "$($eh)h $($em)m $($esec)s" } >> "%PS%"
echo                                     elseif ($em -gt 0) { $cEta = "$($em)m $($esec)s" } >> "%PS%"
echo                                     else               { $cEta = "$($esec)s" } >> "%PS%"
echo                                 } elseif ($cSpeed -le 0 -and $cCur -eq 0) { $cEta = 'Connecting...' } >> "%PS%"
echo                                 $cSpdStr = if ($cSpeed -gt 0) { (Format-Bytes2 $cSpeed) + '/s' } else { '---' } >> "%PS%"
echo                                 [Console]::SetCursorPosition(0, $cRow) >> "%PS%"
echo                                 if ($cPct -ge 0) { >> "%PS%"
echo                                     $cf = [int](($cPct / 100) * 50) >> "%PS%"
echo                                     $cbar = '[' + ('#' * $cf) + ('-' * (50 - $cf)) + ']' >> "%PS%"
echo                                     Write-Host ("  $cbar  $cPct%%").PadRight(78) -ForegroundColor Cyan >> "%PS%"
echo                                 } else { >> "%PS%"
echo                                     Write-Host ('  [--------------------------------------------------]  ???').PadRight(78) -ForegroundColor DarkCyan >> "%PS%"
echo                                 } >> "%PS%"
echo                                 $cDld = Format-Bytes2 $cCur >> "%PS%"
echo                                 $cTot = if ($customTotal -gt 0) { Format-Bytes2 $customTotal } else { '???' } >> "%PS%"
echo                                 Write-Host ("  Downloaded : $cDld / $cTot").PadRight(78) -ForegroundColor Gray >> "%PS%"
echo                                 Write-Host ("  Speed      : $cSpdStr").PadRight(78) -ForegroundColor Gray >> "%PS%"
echo                                 Write-Host ("  ETA        : $cEta").PadRight(78) -ForegroundColor Yellow >> "%PS%"
echo                                 if ([Console]::KeyAvailable) { >> "%PS%"
echo                                     $ck2 = [Console]::ReadKey($true) >> "%PS%"
echo                                     if ($ck2.Key -eq 'Escape') { >> "%PS%"
echo                                         $cr = [System.Windows.Forms.MessageBox]::Show("Download in progress!`nCancel?", 'Confirm Cancel', [System.Windows.Forms.MessageBoxButtons]::YesNo, [System.Windows.Forms.MessageBoxIcon]::Warning) >> "%PS%"
echo                                         if ($cr -eq 'Yes') { $cproc.Kill(); $cCancelled = $true; break } >> "%PS%"
echo                                     } >> "%PS%"
echo                                 } >> "%PS%"
echo                                 Start-Sleep -Milliseconds 500 >> "%PS%"
echo                             } >> "%PS%"
echo                             if (-not $cCancelled) { $cproc.WaitForExit() } >> "%PS%"
echo                             [Console]::CursorVisible = $false >> "%PS%"
echo                             Write-Host '' >> "%PS%"
echo                             if ($cCancelled) { >> "%PS%"
echo                                 Write-Host '  Download cancelled.' -ForegroundColor Yellow >> "%PS%"
echo                             } elseif ($cproc.ExitCode -eq 0) { >> "%PS%"
echo                                 [Console]::SetCursorPosition(0, $cRow) >> "%PS%"
echo                                 $b100 = '[' + ('#' * 50) + ']' >> "%PS%"
echo                                 Write-Host ("  $b100  100%%").PadRight(78) -ForegroundColor Green >> "%PS%"
echo                                 $cTotFmt = if ($customTotal -gt 0) { Format-Bytes2 $customTotal } else { Format-Bytes2 $cLast } >> "%PS%"
echo                                 Write-Host ("  Downloaded : $cTotFmt / $cTotFmt").PadRight(78) -ForegroundColor Green >> "%PS%"
echo                                 Write-Host '  Speed      : Done!'.PadRight(78) -ForegroundColor Green >> "%PS%"
echo                                 Write-Host '  ETA        : Complete!'.PadRight(78) -ForegroundColor Green >> "%PS%"
echo                                 Write-Host '' >> "%PS%"
echo                                 Write-Host "  Saved to: $customOut" -ForegroundColor Green >> "%PS%"
echo                                 try { >> "%PS%"
echo                                     [void][Windows.UI.Notifications.ToastNotificationManager,Windows.UI.Notifications,ContentType=WindowsRuntime] >> "%PS%"
echo                                     $cToast = [Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent([Windows.UI.Notifications.ToastTemplateType]::ToastText02) >> "%PS%"
echo                                     $cTN = $cToast.GetElementsByTagName('text') >> "%PS%"
echo                                     [void]$cTN[0].AppendChild($cToast.CreateTextNode('Win2ISO - Download Complete')) >> "%PS%"
echo                                     [void]$cTN[1].AppendChild($cToast.CreateTextNode("$customFname saved.")) >> "%PS%"
echo                                     [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier('Win2ISO').Show([Windows.UI.Notifications.ToastNotification]::new($cToast)) >> "%PS%"
echo                                 } catch {} >> "%PS%"
echo                             } else { >> "%PS%"
echo                                 Write-Host '  Download failed!' -ForegroundColor Red >> "%PS%"
echo                             } >> "%PS%"
echo                             Write-Host '' >> "%PS%"
echo                             Write-Host '  Press any key to continue...' -ForegroundColor DarkGray >> "%PS%"
echo                             [Console]::ReadKey($true) ^| Out-Null >> "%PS%"
echo                             [Console]::CursorVisible = $false >> "%PS%"
echo                         } >> "%PS%"
echo                     } >> "%PS%"
echo                 } >> "%PS%"
echo             } >> "%PS%"
echo         } >> "%PS%"
echo         continue >> "%PS%"
echo     } >> "%PS%"

echo     switch ($osIdx) { >> "%PS%"
echo         0 { $eds=$vista_ed;  $ax=$vista_x86;  $bx=$vista_x64;  $needArch=$true  } >> "%PS%"
echo         1 { $eds=$win7_ed;   $ax=$win7_x86;   $bx=$win7_x64;   $needArch=$true  } >> "%PS%"
echo         2 { $eds=$win8_ed;   $ax=$win8_x86;   $bx=$win8_x64;   $needArch=$true  } >> "%PS%"
echo         3 { $eds=$win10_ed;  $ax=$win10_x86;  $bx=$win10_x64;  $needArch=$true  } >> "%PS%"
echo         4 { $eds=$win11_ed;  $ax=$null;       $bx=$win11_x64;  $needArch=$false } >> "%PS%"
echo         5 { $eds=$winserver_ed;  $ax=$winserver_x86;  $bx=$winserver_x64;  $needArch=$true  } >> "%PS%"
echo         6 { $eds=$winltsc_ed;    $ax=$winltsc_x86;    $bx=$winltsc_x64;    $needArch=$true  } >> "%PS%"
echo     } >> "%PS%"
echo     $goBackToOS = $false >> "%PS%"
echo     $exitApp = $false >> "%PS%"
echo     while ($true) { >> "%PS%"
echo         $e = Show-Menu $os_names[$osIdx] $eds >> "%PS%"
echo         if ($e -eq -1) { $goBackToOS = $true; break } >> "%PS%"
echo         if ($eds[$e] -eq 'Exit') { $goBackToOS = $true; break } >> "%PS%"
echo         $url  = '' >> "%PS%"
echo         $arch = '' >> "%PS%"

echo         if ($needArch) { >> "%PS%"
echo             while ($true) { >> "%PS%"
echo                 if ($eds[$e] -like '*x86 only*') { >> "%PS%"
echo                     $archMenu = @('x86  (32-bit)','Back') >> "%PS%"
echo                 } else { >> "%PS%"
echo                     $archMenu = @('x86  (32-bit)','x64  (64-bit)','Back') >> "%PS%"
echo                 } >> "%PS%"
echo                 $a = Show-Menu "$($os_names[$o]) / $($eds[$e])" $archMenu >> "%PS%"
echo                 if ($a -eq -1) { break } >> "%PS%"
echo                 if ($a -eq 0) { $arch='x86'; $url=$ax[$e]; break } >> "%PS%"
echo                 if ($a -eq 1 -and $archMenu[$a] -ne 'Back') { $arch='x64'; $url=$bx[$e]; break } >> "%PS%"
echo                 if ($archMenu[$a] -eq 'Back') { break } >> "%PS%"
echo             } >> "%PS%"
echo             if ($a -eq -1) { continue } >> "%PS%"


echo             if ($url -eq 'NONE') { >> "%PS%"
echo                 Clear-Host >> "%PS%"
echo                 Write-Host "" >> "%PS%"
echo                 if ($eds[$e] -like '*x86 only*') { >> "%PS%"
echo                     Write-Host "  This edition is only available in x86 (32-bit)." -ForegroundColor Red >> "%PS%"
echo                 } else { >> "%PS%"
echo                     Write-Host "  No $($arch) variant for this edition." -ForegroundColor Red >> "%PS%"
echo                 } >> "%PS%"
echo                 Write-Host "  Press any key to go back." -ForegroundColor DarkGray >> "%PS%"
echo                 [Console]::ReadKey($true) ^| Out-Null >> "%PS%"
echo                 continue >> "%PS%"
echo             } >> "%PS%"
echo         } else { >> "%PS%"
echo             $arch='x64' >> "%PS%"
echo             $url=$bx[$e] >> "%PS%"
echo         } >> "%PS%"
echo         break >> "%PS%"
echo     } >> "%PS%"
echo     if ($exitApp) { break } >> "%PS%"
echo     if ($goBackToOS) { continue } >> "%PS%"

echo     Clear-Host >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     Write-Host "  Win2ISO - Windows ISO Downloader" -ForegroundColor Green >> "%PS%"
echo     Write-Host "  =================================" -ForegroundColor DarkGreen >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     Write-Host "  OS      : $($os_names[$o])" -ForegroundColor White >> "%PS%"
echo     Write-Host "  Edition : $($eds[$e])"      -ForegroundColor Yellow >> "%PS%"
echo     Write-Host "  Arch    : $arch"             -ForegroundColor Yellow >> "%PS%"
echo     Write-Host "  URL     : $url"              -ForegroundColor DarkGray >> "%PS%"

echo     if ($eds[$e] -like '*8.1 Pro [RTM]*') { >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         Write-Host "  Product Key: XHQ8N-C3MCJ-RQXB6-WCHYG-C9WKB" -ForegroundColor Cyan >> "%PS%"
echo     } elseif (($eds[$e] -like '*Starter*' -and $os_names[$o] -eq 'Windows Vista') -or ($eds[$e] -eq 'Windows 8.1 [RTM]')) { >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         if ($eds[$e] -like '*Starter*' -and $os_names[$o] -eq 'Windows Vista') { >> "%PS%"
echo             Write-Host "  Product Key: X9PYV-YBQRV-9BXWV-TQDMK-QDWK4" -ForegroundColor Cyan >> "%PS%"
echo         } elseif ($eds[$e] -eq 'Windows 8.1 [RTM]') { >> "%PS%"
echo             Write-Host "  Product Key: 334NH-RXG76-64THK-C7CKG-D3VPT" -ForegroundColor Cyan >> "%PS%"
echo         } >> "%PS%"
echo     } >> "%PS%"
echo     Write-Host "" >> "%PS%"

echo     Add-Type -AssemblyName System.Windows.Forms >> "%PS%"
echo     $folderBrowser = New-Object System.Windows.Forms.FolderBrowserDialog >> "%PS%"
echo     $folderBrowser.Description = 'Select folder to save ISO' >> "%PS%"
echo     $folderBrowser.ShowNewFolderButton = $true >> "%PS%"
echo     if ($folderBrowser.ShowDialog() -ne 'OK') { >> "%PS%"
echo         Clear-Host >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         Write-Host "  No folder selected." -ForegroundColor Yellow >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         Write-Host "  Press Enter to go back to edition selection." -ForegroundColor DarkGray >> "%PS%"
echo         Write-Host "" >> "%PS%"
echo         [Console]::ReadKey($true) ^| Out-Null >> "%PS%"
echo         continue >> "%PS%"
echo     } >> "%PS%"
echo     $dir = $folderBrowser.SelectedPath >> "%PS%"
echo     $fname = [IO.Path]::GetFileName($url) >> "%PS%"
echo     $out   = [IO.Path]::Combine($dir, $fname) >> "%PS%"
rem --- fetch file size via HEAD, then launch curl silently, then draw live progress ---
echo     $totalBytes = 0 >> "%PS%"
echo     try { >> "%PS%"
echo         $headReq = [System.Net.WebRequest]::Create($url) >> "%PS%"
echo         $headReq.Method = 'HEAD' >> "%PS%"
echo         $headReq.Timeout = 8000 >> "%PS%"
echo         $headResp = $headReq.GetResponse() >> "%PS%"
echo         $totalBytes = $headResp.ContentLength >> "%PS%"
echo         $headResp.Close() >> "%PS%"
echo     } catch {} >> "%PS%"
echo. >> "%PS%"

echo     $downloadCancelled = $false >> "%PS%"
echo     $p = New-Object Diagnostics.ProcessStartInfo >> "%PS%"
echo     $p.FileName = $curl >> "%PS%"
echo     $p.Arguments = "--silent --location --retry 3 --output `"$out`" `"$url`"" >> "%PS%"
echo     $p.UseShellExecute = $false >> "%PS%"
echo     $proc = [Diagnostics.Process]::Start($p) >> "%PS%"
echo. >> "%PS%"

echo     $startTime    = [DateTime]::Now >> "%PS%"
echo     $lastBytes    = 0 >> "%PS%"
echo     $lastSpeedTime = $startTime >> "%PS%"
echo     $speedBps     = 0 >> "%PS%"
echo. >> "%PS%"
rem --- draw static header on a clean screen, then lock the cursor row ---
echo     Clear-Host >> "%PS%"
echo     [Console]::CursorVisible = $false >> "%PS%"
echo     $sizeLabel = if ($totalBytes -gt 0) { Format-Bytes2 $totalBytes } else { 'Unknown' } >> "%PS%"
echo     Write-Host '' >> "%PS%"
echo     Write-Host '  Win2ISO - Downloading ISO' -ForegroundColor Green >> "%PS%"
echo     Write-Host '  =========================' -ForegroundColor DarkGreen >> "%PS%"
echo     Write-Host '' >> "%PS%"
echo     Write-Host "  Edition : $($eds[$e])" -ForegroundColor Yellow >> "%PS%"
echo     Write-Host "  Arch    : $arch" -ForegroundColor Yellow >> "%PS%"
echo     Write-Host "  Size    : $sizeLabel" -ForegroundColor DarkGray >> "%PS%"
echo     Write-Host "  Saving  : $out" -ForegroundColor DarkGray >> "%PS%"
echo     Write-Host '' >> "%PS%"
echo     Write-Host '  Keep this window open! Press [Esc] to cancel.' -ForegroundColor Red >> "%PS%"
echo     Write-Host '' >> "%PS%"
echo     $progressRow = [Console]::CursorTop >> "%PS%"
echo     Write-Host ('  ' + ' '.PadRight(76)) >> "%PS%"
echo     Write-Host ('  ' + ' '.PadRight(76)) >> "%PS%"
echo     Write-Host ('  ' + ' '.PadRight(76)) >> "%PS%"
echo     Write-Host ('  ' + ' '.PadRight(76)) >> "%PS%"
echo. >> "%PS%"

echo     while (-not $proc.HasExited) { >> "%PS%"
echo         $now          = [DateTime]::Now >> "%PS%"
echo         $curBytes     = 0 >> "%PS%"
echo         if (Test-Path $out) { try { $curBytes = (Get-Item $out -ErrorAction Stop).Length } catch {} } >> "%PS%"
echo         $speedElapsed = ($now - $lastSpeedTime).TotalSeconds >> "%PS%"
echo         if ($speedElapsed -ge 1) { >> "%PS%"
echo             $speedBps      = ($curBytes - $lastBytes) / $speedElapsed >> "%PS%"
echo             $lastBytes     = $curBytes >> "%PS%"
echo             $lastSpeedTime = $now >> "%PS%"
echo         } >> "%PS%"
echo         $pct    = if ($totalBytes -gt 0) { [Math]::Min(100,[int](($curBytes / $totalBytes) * 100)) } else { -1 } >> "%PS%"
echo         $etaStr = 'Calculating...' >> "%PS%"
echo         if ($speedBps -gt 0 -and $totalBytes -gt 0 -and $curBytes -lt $totalBytes) { >> "%PS%"
echo             $etaSec = [int](($totalBytes - $curBytes) / $speedBps) >> "%PS%"
echo             $etaH   = [int]($etaSec / 3600) >> "%PS%"
echo             $etaM   = [int](($etaSec %% 3600) / 60) >> "%PS%"
echo             $etaS   = $etaSec %% 60 >> "%PS%"
echo             if     ($etaH -gt 0) { $etaStr = "$($etaH)h $($etaM)m $($etaS)s" } >> "%PS%"
echo             elseif ($etaM -gt 0) { $etaStr = "$($etaM)m $($etaS)s" } >> "%PS%"
echo             else                 { $etaStr = "$($etaS)s" } >> "%PS%"
echo         } elseif ($speedBps -le 0 -and $curBytes -eq 0) { $etaStr = 'Connecting...' } >> "%PS%"
echo         $speedStr = if ($speedBps -gt 0) { (Format-Bytes2 $speedBps) + '/s' } else { '---' } >> "%PS%"
echo         $dldStr   = Format-Bytes2 $curBytes >> "%PS%"
echo         $totStr   = if ($totalBytes -gt 0) { Format-Bytes2 $totalBytes } else { '???' } >> "%PS%"
echo. >> "%PS%"

echo         [Console]::SetCursorPosition(0, $progressRow) >> "%PS%"
echo         if ($pct -ge 0) { >> "%PS%"
echo             $filled = [int](($pct / 100) * 50) >> "%PS%"
echo             $bar    = '[' + ('#' * $filled) + ('-' * (50 - $filled)) + ']' >> "%PS%"
echo             Write-Host ("  $bar  $pct%%").PadRight(78) -ForegroundColor Cyan >> "%PS%"
echo         } else { >> "%PS%"
echo             Write-Host ("  [--------------------------------------------------]  ???").PadRight(78) -ForegroundColor DarkCyan >> "%PS%"
echo         } >> "%PS%"
echo         Write-Host ("  Downloaded : $dldStr / $totStr").PadRight(78) -ForegroundColor Gray >> "%PS%"
echo         Write-Host ("  Speed      : $speedStr").PadRight(78) -ForegroundColor Gray >> "%PS%"
echo         Write-Host ("  ETA        : $etaStr").PadRight(78) -ForegroundColor Yellow >> "%PS%"
echo. >> "%PS%"

echo         if ([System.Console]::KeyAvailable) { >> "%PS%"
echo             $key = [System.Console]::ReadKey($true) >> "%PS%"
echo             if ($key.Key -eq 'Escape') { >> "%PS%"
echo                 $result = [System.Windows.Forms.MessageBox]::Show("Download in progress!`nAre you sure you want to cancel?", 'Confirm Cancel', [System.Windows.Forms.MessageBoxButtons]::YesNo, [System.Windows.Forms.MessageBoxIcon]::Warning) >> "%PS%"
echo                 if ($result -eq 'Yes') { >> "%PS%"
echo                     $proc.Kill() >> "%PS%"
echo                     $downloadCancelled = $true >> "%PS%"
echo                     break >> "%PS%"
echo                 } >> "%PS%"
echo             } >> "%PS%"
echo         } >> "%PS%"
echo         Start-Sleep -Milliseconds 500 >> "%PS%"
echo     } >> "%PS%"
echo     if (-not $downloadCancelled) { $proc.WaitForExit() } >> "%PS%"
echo. >> "%PS%"

rem --- final frame: show 100%% or last known state ---
echo     if (-not $downloadCancelled -and $proc.ExitCode -eq 0) { >> "%PS%"
echo         [Console]::SetCursorPosition(0, $progressRow) >> "%PS%"
echo         if ($totalBytes -gt 0) { >> "%PS%"
echo             $bar = '[' + ('#' * 50) + ']' >> "%PS%"
echo             Write-Host ("  $bar  100%%").PadRight(78) -ForegroundColor Green >> "%PS%"
echo             $totFmt = Format-Bytes2 $totalBytes >> "%PS%"
echo             Write-Host ("  Downloaded : $totFmt / $totFmt").PadRight(78) -ForegroundColor Green >> "%PS%"
echo         } else { >> "%PS%"
echo             Write-Host '  [##################################################]  Done!'.PadRight(78) -ForegroundColor Green >> "%PS%"
echo             Write-Host '  Downloaded successfully.'.PadRight(78) -ForegroundColor Green >> "%PS%"
echo         } >> "%PS%"
echo         Write-Host '  Speed      : Done!'.PadRight(78) -ForegroundColor Green >> "%PS%"
echo         Write-Host '  ETA        : Complete!'.PadRight(78) -ForegroundColor Green >> "%PS%"
echo     } >> "%PS%"
echo     [Console]::CursorVisible = $false >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     if ($downloadCancelled) { >> "%PS%"
echo         Write-Host "  Download cancelled. Returning to edition selection..." -ForegroundColor Yellow >> "%PS%"
echo         Start-Sleep -Seconds 1 >> "%PS%"
echo         continue >> "%PS%"
echo     } >> "%PS%"
echo     if ($proc.ExitCode -eq 0) { >> "%PS%"
echo         Write-Host "  Done! Saved to: $out" -ForegroundColor Green >> "%PS%"

echo         try { >> "%PS%"
echo             [void][Windows.UI.Notifications.ToastNotificationManager,Windows.UI.Notifications,ContentType=WindowsRuntime] >> "%PS%"
echo             $data = [Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent([Windows.UI.Notifications.ToastTemplateType]::ToastText02) >> "%PS%"
echo             $total = $data.GetElementsByTagName('text') >> "%PS%"
echo             [void]$total[0].AppendChild($data.CreateTextNode('Win2ISO - Download Complete')) >> "%PS%"
echo             [void]$total[1].AppendChild($data.CreateTextNode("$($eds[$e]) ($arch) saved.")) >> "%PS%"
echo             [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier('Win2ISO').Show([Windows.UI.Notifications.ToastNotification]::new($data)) >> "%PS%"
echo         } catch {} >> "%PS%"
echo     } else { >> "%PS%"
echo         Write-Host "  Download failed! (exit: $($proc.ExitCode))" -ForegroundColor Red >> "%PS%"
echo         Write-Host "  Make sure the URL is not still a PLACEHOLDER." -ForegroundColor Yellow >> "%PS%"
echo     } >> "%PS%"
echo     Write-Host "" >> "%PS%"
echo     Write-Host "  Press any key to return to menu..." -ForegroundColor DarkGray >> "%PS%"
echo     [Console]::ReadKey($true) ^| Out-Null >> "%PS%"
echo     [Console]::CursorVisible = $false >> "%PS%"
echo } >> "%PS%"

echo Clear-Host >> "%PS%"
echo Write-Host "" >> "%PS%"
echo Write-Host "  Thanks for using Win2ISO!" -ForegroundColor Green >> "%PS%"
echo Write-Host "  Goodbye." -ForegroundColor DarkGray >> "%PS%"
echo Write-Host "" >> "%PS%"
echo [Console]::CursorVisible = $true >> "%PS%"
echo Start-Sleep -Seconds 1 >> "%PS%"

rem this writes a new script in temp
del "%CURL_INSTALLER%" 2>nul
(
    echo @echo off
    echo setlocal EnableDelayedExpansion
    echo.
    echo net session ^>nul 2^>^&1
    echo if %%errorLevel%% NEQ 0 (
    echo     echo [INFO] Requesting administrator privileges...
    echo     powershell -NoProfile -ExecutionPolicy Bypass -Command "Start-Process -FilePath '%%~f0' -Verb RunAs"
    echo     exit /b
    echo ^)
    echo.
    echo echo ============================================
    echo echo              cURL Installer
    echo echo ============================================
    echo echo.
    echo.
    echo curl --version ^>nul 2^>^&1
    echo if %%errorLevel%% EQU 0 (
    echo     echo [INFO] curl is already installed:
    echo     curl --version ^| findstr /index "curl"
    echo     echo.
    echo     choice /C YN /M "Do you want to reinstall/update curl?"
    echo     if !errorLevel! EQU 2 (
    echo         echo Exiting...
    echo         pause
    echo         exit /b 0
    echo     ^)
    echo ^)
    echo.
    echo set "INSTALL_DIR=%%SYSTEMROOT%%\System32"
    echo set "TEMP_DIR=%%TEMP%%\curl_install"
    echo set "CURL_ZIP=%%TEMP_DIR%%\curl.zip"
    echo set "EXTRACT_DIR=%%TEMP_DIR%%\extracted"
    echo.
    echo if exist "%%TEMP_DIR%%" rd /s /q "%%TEMP_DIR%%"
    echo mkdir "%%TEMP_DIR%%"
    echo mkdir "%%EXTRACT_DIR%%"
    echo.
    echo echo [INFO] Downloading curl for Windows ^(64-bit^)...
    echo powershell -NoProfile -ExecutionPolicy Bypass -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri 'https://curl.se/windows/dl-8.11.1_1/curl-8.11.1_1-win64-mingw.zip' -OutFile '%%CURL_ZIP%%' -UseBasicParsing"
    echo.
    echo if not exist "%%CURL_ZIP%%" (
    echo     echo [ERROR] Download failed. Check your internet connection.
    echo     pause
    echo     exit /b 1
    echo ^)
    echo echo [INFO] Download successful.
    echo.
    echo echo [INFO] Extracting archive...
    echo powershell -NoProfile -ExecutionPolicy Bypass -Command "Expand-Archive -LiteralPath '%%CURL_ZIP%%' -DestinationPath '%%EXTRACT_DIR%%' -Force"
    echo.
    echo if %%errorLevel%% NEQ 0 (
    echo     echo [ERROR] Expand-Archive failed.
    echo     pause
    echo     exit /b 1
    echo ^)
    echo.
    echo echo [INFO] Locating curl.exe in bin folder...
    echo set "CURL_BIN_SRC="
    echo for /r "%%EXTRACT_DIR%%" %%%%F in ^(curl.exe^) do ^(
    echo     echo %%%%~dpF ^| findstr /index "\\bin\\" ^>nul
    echo     if !errorLevel! EQU 0 ^(
    echo         set "CURL_BIN_SRC=%%%%~dpF"
    echo     ^)
    echo ^)
    echo.
    echo if not defined CURL_BIN_SRC (
    echo     echo [ERROR] Could not find curl.exe inside a bin folder.
    echo     echo [DEBUG] All curl.exe locations found:
    echo     for /r "%%EXTRACT_DIR%%" %%%%F in ^(curl.exe^) do echo   %%%%F
    echo     pause
    echo     exit /b 1
    echo ^)
    echo.
    echo echo [INFO] Found bin folder: %%CURL_BIN_SRC%%
    echo.
    echo echo [INFO] Installing to %%INSTALL_DIR%%...
    echo copy /Y "%%CURL_BIN_SRC%%curl.exe" "%%INSTALL_DIR%%\" ^>nul
    echo copy /Y "%%CURL_BIN_SRC%%*.dll"    "%%INSTALL_DIR%%\" ^>nul 2^>^&1
    echo copy /Y "%%CURL_BIN_SRC%%*.crt"    "%%INSTALL_DIR%%\" ^>nul 2^>^&1
    echo.
    echo if not exist "%%INSTALL_DIR%%\curl.exe" (
    echo     echo [ERROR] Failed to copy curl.exe to %%INSTALL_DIR%%.
    echo     pause
    echo     exit /b 1
    echo ^)
    echo.
    echo echo [INFO] Cleaning up temp files...
    echo rd /s /q "%%TEMP_DIR%%" ^>nul 2^>^&1
    echo.
    echo echo.
    echo echo ============================================
    echo echo        Installation Complete!
    echo echo ============================================
    echo echo.
    echo echo Installed to: %%INSTALL_DIR%%\curl.exe
    echo echo.
    echo curl --version
    echo echo.
    echo pause
    echo exit /b 0
) > "%CURL_INSTALLER%"
:run_ps
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%PS%" "%~f0"
del "%CURL_INSTALLER%" 2>nul
endlocal
